---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.37.0
    hooks:
      - id: markdownlint
        args: [--config=.linter-config/markdownlint-cli-config.yml]
        name: markdownlint
        description: "Checks the style of Markdown/Commonmark files."
        entry: markdownlint
        language: node
        types: [markdown]
        minimum_pre_commit_version: 0.15.0
      - id: markdownlint-fix
        args: [--config=.linter-config/markdownlint-cli-config.yml]
        name: markdownlint-fix
        description: "Fixes the style of Markdown/Commonmark files."
        entry: markdownlint --fix
        language: node
        types: [markdown]
        minimum_pre_commit_version: 0.15.0
